## Configuration file used by the centralized impedance controller

rate: 500 # [Hz]

arm1_base_name: arm1_base

arm2_base_name: arm2_base

arm1_EE_name: arm1_tcp

arm2_EE_name: arm2_tcp

arm1_wrench_topic: /arm1/wrench

arm2_wrench_topic: /arm2/wrench

arm1_speed_slider: 0.2

arm2_speed_slider: 0.2

reversed_joints: true

handover_start_idx: 801

handover_end_idx: 1627

# basi vicine  con nuova piastra
arm1_base_in_world:
  x: 0.535763
  y: -0.284
  z: 0.03473
  roll: 0.0
  pitch: 0.261799
  yaw: 1.57079632679

# basi vicine  con nuova piastra
arm2_base_in_world:
  x: 0.535763
  y: 0.284
  z: 0.03473
  roll: 0.0
  pitch: 0.261799
  yaw: 1.57079632679

## PI control coefficients
arm1_PI_controller:
  KP_diag:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  KI_diag:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0

arm2_PI_controller:
  KP_diag:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0

  KI_diag:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
